apiVersion: v1
kind: Service
metadata:
  name: {{ include "sfdemo.fullname" . }}
  labels:
    {{- include "sfdemo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  selector:
    {{- include "sfdemo.selectorLabels" . | nindent 4 }}
